# Netlify 配置文件

[build]
  # 部署目录，构建后的文件将发布到此目录
  publish = "dist"
  # 构建命令，安装依赖并执行构建
  command = "pnpm install && pnpm run build"

# 重定向规则，将所有未匹配的路径重定向到 index.html，用于单页应用路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP 响应头配置
[[headers]]
  # 适用于所有路径
  for = "/*"
  [headers.values]
    # 防止浏览器MIME类型嗅探，强制使用Content-Type
    X-Content-Type-Options = "nosniff"
    # 防止点击劫持，DENY表示不允许任何框架加载此页面
    X-Frame-Options = "DENY"
    # 启用XSS保护，并阻止检测到的攻击
    X-XSS-Protection = "1; mode=block"
    # 控制referrer信息发送策略
    Referrer-Policy = "strict-origin-when-cross-origin"
    # 强制客户端通过HTTPS连接，并缓存此策略
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# 针对 /assets/ 路径下的文件设置缓存头
[[headers]]
  for = "/assets/*"
  [headers.values]
    # 缓存控制：公共缓存，最大缓存时间一年，文件内容不可变
    Cache-Control = "public, max-age=31536000, immutable"